FROM python:3.12-slim
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    build-essential \
    libffi-dev \
    libssl-dev \
    python3-dev \
    netcat-openbsd
WORKDIR /app
COPY requirements-target.txt .
RUN pip install --no-cache-dir -r requirements-target.txt
COPY . .
CMD ["target-csv", "--config", "/app/backend/config/target-csv-config.json"]
