FROM python:3.10-slim

# Install necessary packages, including MySQL client utilities
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    build-essential \
    libffi-dev \
    libssl-dev \
    python3-dev \
    netcat-openbsd \
    default-mysql-client

WORKDIR /app
COPY requirements-tap.txt .
RUN pip install --no-cache-dir -r requirements-tap.txt
COPY . .
COPY wait-for-mysql.sh /app/wait-for-mysql.sh
RUN chmod +x /app/wait-for-mysql.sh
CMD ["sh", "-c", "./wait-for-mysql.sh mysql && tap-mysql --config /app/backend/config/tap-mysql-csv-config.json"]
